// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CustomTableCellApp {
 
 
 // Base type probably should be MonoTouch.UIKit.UITableViewCell or subclass
 [MonoTouch.Foundation.Register("CustomCell1")]
 public partial class CustomCell1 {
     
     private MonoTouch.UIKit.UILabel __mt_mainLabel;
     
     private MonoTouch.UIKit.UILabel __mt_subLabel;
     
     #pragma warning disable 0169
     [MonoTouch.Foundation.Connect("mainLabel")]
     private MonoTouch.UIKit.UILabel mainLabel {
         get {
             this.__mt_mainLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("mainLabel")));
             return this.__mt_mainLabel;
         }
         set {
             this.__mt_mainLabel = value;
             this.SetNativeField("mainLabel", value);
         }
     }
     
     [MonoTouch.Foundation.Connect("subLabel")]
     private MonoTouch.UIKit.UILabel subLabel {
         get {
             this.__mt_subLabel = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("subLabel")));
             return this.__mt_subLabel;
         }
         set {
             this.__mt_subLabel = value;
             this.SetNativeField("subLabel", value);
         }
     }
 }
}
